name: 'Run Parasoft C/C++test'
description: 'A GitHub Action for running Parasoft C/C++test to ensure code quality and compliance with MISRA, AUTOSAR, CERT, and more.'
author: 'Parasoft'
branding:
  icon: 'aperture'
  color: 'blue'
inputs:
  installDir:
    description: 'Installation folder of Parasoft C/C++test. If not specified, the cpptestcli executable must be added to $PATH.'
    required: false
  workingDir:
    description: 'Working directory for running C/C++test.'
    required: false
    default: ${{ github.workspace }}
  compilerConfig:
    description: 'Identifier of a compiler configuration. Ensure you specify the configuration that matches your compiler.'
    required: false
    default: 'gcc_9-64' 
  testConfig:
    description: 'Test configuration to be used for code analysis.'
    required: false
    default: 'builtin://Recommended Rules'
  reportDir:
    description: 'Output folder for reports from code analysis.'
    required: false
    default: 'reports'
  reportFormat:
    description: 'Format of reports from code analysis.'
    required: false
    default: 'xml,html,sarif'
  input:
    description: 'Input scope for analysis (typically, cpptestscan.bdf or compile_commands.json, depending on the project type and the build system).'
    required: false
    default: 'cpptestscan.bdf'
  additionalParams:
    description: 'Additional parameters for the cpptestcli executable.'
    required: false
    default: ''
  commandLinePattern:
    description: 'Command line pattern for running C/C++test.'
    required: false 
    default: '${cpptestcli} -compiler "${compilerConfig}" -config "${testConfig}" -property report.format=${reportFormat} -report "${reportDir}" -module . -input "${input}" ${additionalParams}'
runs:
  using: 'node12'
  main: 'dist/index.js'
